const $=s=>document.querySelector(s),modal=$('#modal'),form=$('#form'),hostsEl=$('#hosts'),terminalArea=$('#terminals'),workspace=$('#workspace'),welcome=$('#welcome'),tabsEl=$('#tabs'),statusEl=$('#status');
window.addEventListener('error',e=>{const box=$('#errorToast');if(box){box.textContent='页面错误：'+e.message;box.hidden=false}});
let hosts=JSON.parse(localStorage.getItem('nekssh.hosts')||'[]'),tabs=[],activeId=null,editingIndex=-1;
function save(){localStorage.setItem('nekssh.hosts',JSON.stringify(hosts));renderHosts()}
function renderHosts(){hostsEl.innerHTML='';hosts.forEach((h,i)=>{const el=document.createElement('div');el.className='host';el.title='点击连接';el.innerHTML=`<span><b>${esc(h.name)}</b><small>${esc(h.username)}@${esc(h.host)}:${h.port}</small></span><span class="host-actions"><button class="connect-host" data-action="connect">连接</button><button data-action="edit" title="编辑">✎</button><button data-action="delete" title="删除">×</button></span>`;el.onclick=e=>{const a=e.target.dataset.action;if(a==='delete'){e.stopPropagation();if(confirm(`删除“${h.name}”？`)){hosts.splice(i,1);save()}}else if(a==='edit'){e.stopPropagation();openForm(h,i,'edit')}else openForm(h,i,'connect')};hostsEl.append(el)})}
function openForm(h={},i=-1,mode='new'){editingIndex=i;form.reset();form.name.value=h.name||'';form.host.value=h.host||'';form.port.value=h.port||22;form.username.value=h.username||'';$('#formTitle').textContent=mode==='edit'?'编辑并连接':mode==='connect'?`连接 ${h.name}`:'新建 SSH 连接';$('#connectButton').textContent=mode==='connect'?'连接':'保存并连接';modal.showModal();setTimeout(()=>form.password.focus(),50)}
$('#newHost').onclick=()=>openForm();$('#welcomeNew').onclick=()=>openForm();$('#cancel').onclick=()=>modal.close();
form.onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form)),stored={name:d.name.trim(),host:d.host.trim(),port:Number(d.port),username:d.username.trim()};editingIndex<0?hosts.push(stored):hosts[editingIndex]=stored;save();modal.close();createTab({...stored,password:d.password,privateKey:d.privateKey,passphrase:d.passphrase})};
function createTab(connection){const id=makeId(),pane=document.createElement('div');pane.className='terminal-pane';terminalArea.append(pane);const term=new Terminal({cursorBlink:true,fontSize:14,scrollback:5000,fontFamily:'ui-monospace,SFMono-Regular,Consolas,monospace',theme:{background:'#0b0e14',foreground:'#d8dee9',cursor:'#73daca',selectionBackground:'#33445c'}}),fit=new FitAddon.FitAddon();term.loadAddon(fit);term.open(pane);const tab={id,connection,pane,term,fit,ws:null,state:'connecting',path:'.',entries:[],inputBuffer:''};tabs.push(tab);term.onData(data=>{if(tab.ws?.readyState!==1)return;trackCommand(tab,data);tab.ws.send(JSON.stringify({type:'input',data}))});term.onResize(({cols,rows})=>tab.ws?.readyState===1&&tab.ws.send(JSON.stringify({type:'resize',cols,rows})));activateTab(id);connectTab(tab)}
function connectTab(tab){tab.state='connecting';updateTab(tab);tab.term.writeln(`\x1b[90m正在连接 ${tab.connection.host}...\x1b[0m`);const proto=location.protocol==='https:'?'wss:':'ws:',ws=new WebSocket(`${proto}//${location.host}/ws`);tab.ws=ws;ws.onopen=()=>ws.send(JSON.stringify({type:'connect',connection:{...tab.connection,cols:tab.term.cols,rows:tab.term.rows}}));ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.type==='output')tab.term.write(m.data);if(m.type==='connected'){tab.state='connected';updateTab(tab);listFiles(tab,'.')}if(m.type==='error'){tab.term.writeln(`\r\n\x1b[31m${m.message}\x1b[0m`);tab.state='error';updateTab(tab);showError(m.message)}if(m.type==='sftp_error')showError(m.message);if(m.type==='sftp_list'){tab.path=m.path;tab.entries=m.entries||[];if(tab.id===activeId)renderFiles(tab)}if(m.type==='sftp_uploaded'){showNotice(m.message);listFiles(tab,tab.path)}if(m.type==='sftp_download')saveDownload(m.name,m.data);if(m.type==='sftp_estimate'&&confirm(`目录包含 ${m.count} 个文件，共 ${formatSize(m.size)}。是否压缩为 ZIP 下载？`))tab.ws.send(JSON.stringify({type:'sftp_download_dir',path:m.path}))};ws.onclose=()=>{if(tab.ws!==ws)return;if(tab.state!=='error')tab.state='closed';tab.term.writeln('\r\n\x1b[90m[连接已关闭，可点击右上角重连]\x1b[0m');updateTab(tab)}}
function closeTab(id){const i=tabs.findIndex(t=>t.id===id);if(i<0)return;const t=tabs[i];t.ws?.close();t.term.dispose();t.pane.remove();tabs.splice(i,1);if(activeId===id)activeId=tabs[Math.max(0,i-1)]?.id||null;activeId?activateTab(activeId):showWelcome()}
function activateTab(id){activeId=id;welcome.style.display='none';workspace.style.display='flex';workspace.classList.add('files-open');$('#filesButton').textContent='收起文件';tabs.forEach(t=>t.pane.classList.toggle('active',t.id===id));renderTabs();const t=tabs.find(t=>t.id===id);if(t){requestAnimationFrame(()=>{t.fit.fit();t.term.focus()});setHeader(t);renderFiles(t)}}
function renderTabs(){tabsEl.innerHTML='';tabs.forEach(t=>{const el=document.createElement('button');el.className='tab'+(t.id===activeId?' active':'');el.innerHTML=`<i class="dot ${t.state}"></i><span>${esc(t.connection.name)}</span><b>×</b>`;el.onclick=e=>e.target.tagName==='B'?closeTab(t.id):activateTab(t.id);tabsEl.append(el)})}
function updateTab(t){renderTabs();if(t.id===activeId)setHeader(t)}function setHeader(t){const x={connecting:'正在连接',connected:'已连接',error:'连接失败',closed:'已断开'};statusEl.className=t.state;statusEl.textContent='● '+x[t.state];$('#reconnect').hidden=!['error','closed'].includes(t.state);$('#filesButton').hidden=t.state!=='connected'}
function showWelcome(){activeId=null;workspace.style.display='none';welcome.style.display='block';statusEl.className='';statusEl.textContent='● 就绪';$('#reconnect').hidden=true;$('#filesButton').hidden=true;renderTabs()}
function showError(message){const box=$('#errorToast');box.textContent='连接失败：'+message;box.hidden=false;clearTimeout(showError.timer);showError.timer=setTimeout(()=>box.hidden=true,8000)}
function showNotice(message){const box=$('#errorToast');box.textContent=message;box.hidden=false;clearTimeout(showError.timer);showError.timer=setTimeout(()=>box.hidden=true,3000)}
function activeTab(){return tabs.find(t=>t.id===activeId)}function listFiles(t,path){if(t?.ws?.readyState===1)t.ws.send(JSON.stringify({type:'sftp_list',path}))}
function renderFiles(t){$('#filePath').textContent=t.path;const list=$('#fileList');list.innerHTML='<div class="file-head"><span>名称</span><span>权限</span><span>用户</span><span>用户组</span><span>大小</span><span>修改时间</span></div>';t.entries.forEach(f=>{const row=document.createElement('div');row.className='file-row';row.innerHTML=`<span>${f.directory?'📁':'📄'} ${esc(f.name)}</span><span>${esc(f.mode||'-')}</span><span>${esc(f.owner||'-')}</span><span>${esc(f.group||'-')}</span><span>${f.directory?'-':formatSize(f.size)}</span><span>${new Date(f.modified).toLocaleString()}</span>`;row.ondblclick=()=>f.directory?listFiles(t,f.path):downloadFile(t,f.path);row.oncontextmenu=e=>showContextMenu(e,t,f);list.append(row)})}
function downloadFile(t,path){t.ws.send(JSON.stringify({type:'sftp_download',path}))}function saveDownload(name,data){const bytes=Uint8Array.from(atob(data),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes])),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function showContextMenu(event,tab,file){event.preventDefault();const menu=$('#contextMenu');menu.style.left=event.clientX+'px';menu.style.top=event.clientY+'px';menu.hidden=false;menu.querySelector('[data-action="open"]').hidden=!file.directory;menu.onclick=e=>{const action=e.target.dataset.action;if(action==='open')listFiles(tab,file.path);if(action==='download')file.directory?tab.ws.send(JSON.stringify({type:'sftp_estimate',path:file.path})):downloadFile(tab,file.path);menu.hidden=true}}
document.addEventListener('click',e=>{if(!e.target.closest('#contextMenu'))$('#contextMenu').hidden=true});document.addEventListener('contextmenu',e=>{if(!e.target.closest('.file-row'))$('#contextMenu').hidden=true});
function formatSize(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB'}
$('#filesButton').onclick=()=>{workspace.classList.toggle('files-open');const t=activeTab();if(t){renderFiles(t);setTimeout(()=>t.fit.fit(),0)}};$('#fileRefresh').onclick=()=>{const t=activeTab();listFiles(t,t.path)};$('#fileUp').onclick=()=>{const t=activeTab();if(t)listFiles(t,t.path==='.'?'..':t.path.replace(/\/?[^/]+\/?$/,'')||'/')};$('#fileUpload').onchange=async e=>{const file=e.target.files[0],t=activeTab();if(!file||!t)return;if(file.size>10*1024*1024){showError('单个文件不能超过 10 MB');return}const data=bytesToBase64(new Uint8Array(await file.arrayBuffer()));t.ws.send(JSON.stringify({type:'sftp_upload',path:t.path,name:file.name,data}));e.target.value=''};
function bytesToBase64(bytes){let binary='';for(let i=0;i<bytes.length;i+=32768)binary+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(binary)}
function trackCommand(tab,data){for(const ch of data){if(ch==='\r'||ch==='\n'){const command=tab.inputBuffer.trim();tab.inputBuffer='';const match=command.match(/^cd(?:\s+(.*))?$/);if(match)setTimeout(()=>syncCd(tab,match[1]),350)}else if(ch==='\x7f'){tab.inputBuffer=tab.inputBuffer.slice(0,-1)}else if(ch==='\x03'||ch==='\x15'){tab.inputBuffer=''}else if(ch>=' '&&ch!=='\x7f'){tab.inputBuffer+=ch}}}
function syncCd(tab,rawTarget){let target=(rawTarget||'~').trim();if((target.startsWith('"')&&target.endsWith('"'))||(target.startsWith("'")&&target.endsWith("'")))target=target.slice(1,-1);if(target==='~'||target==='')target='.';else if(target.startsWith('~/'))target='./'+target.slice(2);else if(!target.startsWith('/'))target=tab.path.replace(/\/$/,'')+'/'+target;listFiles(tab,target)}
$('#filesButton').onclick=()=>{workspace.classList.toggle('files-open');$('#filesButton').textContent=workspace.classList.contains('files-open')?'收起文件':'展开文件';const t=activeTab();if(t)setTimeout(()=>t.fit.fit(),0)};
function makeId(){if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const bytes=new Uint8Array(16);crypto.getRandomValues(bytes);return Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('')}
$('#reconnect').onclick=()=>{const t=tabs.find(t=>t.id===activeId);if(t){t.ws?.close();connectTab(t)}};new ResizeObserver(()=>tabs.find(t=>t.id===activeId)?.fit.fit()).observe(terminalArea);function esc(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}renderHosts();showWelcome();
